reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$0 /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$1 /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$2 /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$3 /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$4 /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$5 /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$6 /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$7 /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$8 /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$9 /d 0 /f
reg add "HKEY_LOCAL_MACHINE\SECURITY\CACHE" /t REG_BINARY /v NL$10 /d 0 /f
reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon" /v CachedLogonsCount /t REG_SZ /d 0 /f
